#!/bin/bash

### This script is called before the user installs the application.

# Pre-create the default storage directory to ensure permissions and availability
DEFAULT_STORAGE="${TRIM_APPDEST_VOL}/@appshare/ting-reader/storage"
DEFAULT_DATA="${TRIM_APPDEST_VOL}/@appshare/ting-reader/data"
DEFAULT_PLUGINS="${TRIM_APPDEST_VOL}/@appshare/ting-reader/plugins"
DEFAULT_TEMP="${TRIM_APPDEST_VOL}/@appshare/ting-reader/temp"

echo "Pre-creating directories..."
mkdir -p "$DEFAULT_STORAGE"
mkdir -p "$DEFAULT_DATA"
mkdir -p "$DEFAULT_PLUGINS"
mkdir -p "$DEFAULT_TEMP"

exit 0